---
- name: Include basic vars for localhost hosts
  hosts: localhost
  tasks:
    - name: Include variables
      include_vars: vars/main.yaml

- name: Create instances
  hosts: localhost
  roles:
    - role: create_os_resources

- name: Include basic vars for all hosts
  hosts: all
  tasks:
  - name: Include variables
    include_vars: vars/main.yaml

- name: Deploy monitoring master machine
  hosts: master
  become_user: root
  become: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  roles:
    - { role: common }
    - { role: docker_compose }

- name: Deploy workload slaves
  hosts: slaves-daemon-set
  become_user: root
  become: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  roles:
    - { role: common }
