---
- name: Create instances
  hosts: localhost
  vars_files:
    - "vars/main.yaml"
  roles:
#    - role: create_os_resources
#      tags: ['init-base-os-resources']
#
    - role: create_os_resources
      vars:
        group: 'master'
        instance_count: 1
        instance_name: 'prometheus-master'
        assign_floating_ip: true

    - role: create_os_resources
      vars:
        group: 'slaves-daemon-set'
        instance_name: 'prometheus-slave'
        assign_floating_ip: true

    - role: create_os_resources
      vars:
        group: 'slaves-general-load'
        instance_count: 1
        instance_name: 'prometheus-slave'
        assign_floating_ip: false

- name: Deploy monitoring master machine
  hosts: master
  become_user: root
  become: yes
  vars_files:
    - "vars/main.yaml"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  roles:
    - { role: common }
    - { role: squid }
    - { role: docker }
    - { role: docker_compose }

- name: Deploy daemon set slaves
  hosts: slaves-daemon-set
  become_user: root
  become: yes
  vars_files:
    - "vars/main.yaml"
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  roles:
    - { role: common }

- name: Deploy workload slaves
  hosts: slaves-general-load
  become_user: root
  become: yes
  vars_files:
    - "vars/main.yaml"
  roles:
  - role: common
    vars:
      http_proxy: "http://{{ hostvars[groups['master'][0]]['private_ip'] }}:3128"
      https_proxy: "http://{{ hostvars[groups['master'][0]]['private_ip'] }}:3128"
