---
- name: Include basic vars for localhost hosts
  hosts: localhost
  tasks:
    - name: Include variables
      include_vars: vars/main.yaml

- name: Create instances
  hosts: localhost
  roles:
    - role: create_os_resources
