---
# TODO: split on several plays
- name: Create os resources
  hosts: localhost
  vars_files:
    - "vars/main.yaml"
  roles:
    - role: create_os_resources

- name: Create instances
  hosts: localhost
  vars_files:
    - "vars/main.yaml"
  roles:
    # TODO: run it async way
    - role: create_os_instances
      vars:
        group: 'master'
        instance_count: 1
        instance_name: 'prometheus-master'
        assign_floating_ip: true

    - role: create_os_instances
      vars:
        group: 'slaves-daemon-set'
        instance_name: 'prometheus-slave'
        assign_floating_ip: true

    - role: create_os_instances
      vars:
        group: 'slaves-general-load'
        instance_count: 1
        instance_name: 'prometheus-slave'
        assign_floating_ip: false

- name: Deploy monitoring master machine
  hosts: master
  become_user: root
  become: yes
  vars_files:
    - "vars/main.yaml"
#  environment:
#    http_proxy: "{{ external_proxy_address }}"
#    https_proxy: "{{ external_proxy_address }}"
  roles:
    - role: common
    - role: squid
      vars:
        proxy_host: "{{ proxy_host }}"
        proxy_port: "{{ proxy_port }}"
    - role: docker
    - role: docker_compose

- name: Deploy daemon set slaves
  hosts: slaves-daemon-set
  become_user: root
  become: yes
  vars_files:
    - "vars/main.yaml"
  environment:
    http_proxy: "{{ external_proxy_address }}"
    https_proxy: "{{ external_proxy_address }}"
  roles:
    - role: common

- name: Deploy workload slaves
  hosts: slaves-general-load
  become_user: root
  become: yes
  vars_files:
    - "vars/main.yaml"
  roles:
  - role: common
    vars:
      # TODO (msenin): remove hardcoded protocol and port number
      http_proxy: "http://{{ hostvars[groups['master'][0]]['private_ip'] }}:3128"
      https_proxy: "http://{{ hostvars[groups['master'][0]]['private_ip'] }}:3128"
