#!/bin/bash

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

packages="prometheus-node-exporter
docker-ce
python3-pip
docker-compose
openssh-server"

apt -y install $packages

apt -y autoremove && apt autoclean

python /tmp/in_target.d/extra-data.d/docker_pull.py prom/prometheus:v2.7.2
python /tmp/in_target.d/extra-data.d/docker_pull.py prom/alertmanager:v0.15.0
python /tmp/in_target.d/extra-data.d/docker_pull.py alerta/alerta-web:8.1.0
python /tmp/in_target.d/extra-data.d/docker_pull.py mongo:4.2
