#!/bin/bash

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

packages="prometheus-node-exporter
docker-ce
python3-pip
docker-compose
openssh-server"

apt -y install $packages

apt -y autoremove && apt autoclean

wget https://raw.githubusercontent.com/dpovolotskiy/openstack-workload-monitoring/master/docker_pull.py

python docker_pull.py prom/prometheus:v2.7.2
python docker_pull.py prom/alertmanager:v0.15.0
python docker_pull.py alerta/alerta-web
python docker_pull.py mongo

rm -f /docker_pull.py
