#!/bin/bash

useradd -s /bin/bash -d /home/demo/ -m -G sudo demo

echo demo:demo | chpasswd

sed -i 's/PasswordAuthentication .*/PasswordAuthentication yes/g' /etc/ssh/sshd_config

mkdir -p /home/ubuntu/monitoring/{data,config}
mkdir -p /home/ubuntu/monitoring/data/prometheus/

chown -R nobody:root /home/ubuntu/monitoring/data/prometheus/
chgrp nogroup /home/ubuntu/monitoring/config/

cp /tmp/in_target.d/extra-data.d/alertmanager.yml /home/ubuntu/monitoring/config/

chown -R root:root /home/ubuntu/monitoring/config/alertmanager.yml
chmod 0644 /home/ubuntu/monitoring/config/alertmanager.yml

cp /tmp/in_target.d/extra-data.d/rules.conf /home/ubuntu/monitoring/config/

chown -R root:root /home/ubuntu/monitoring/config/rules.conf
chmod 0644 /home/ubuntu/monitoring/config/rules.conf

cp /tmp/in_target.d/extra-data.d/docker-compose.yml /home/ubuntu/monitoring/

chown -R root:root /home/ubuntu/monitoring/docker-compose.yml
chmod 0644 /home/ubuntu/monitoring/docker-compose.yml

cp /tmp/in_target.d/extra-data.d/import_docker_images.sh /

chown -R root:root /import_docker_images.sh
chmod +x /import_docker_images.sh
