- name: Create new instance with prometheus, alert manager and alerta
  register: "os_hosts"
  os_server:
    state: present
    timeout: 200
    name: "{{ instance_name }}"
    cloud: "{{ cloud }}"
    image: "{{ image_id }}"
    key_name: "{{ key_name }}"
    flavor: "{{ flavor_id }}"
    security_groups: "{{ security_groups }}"
    floating_ip_pools: "{{ floating_ip_pools }}"
    nics: [ net-id: "{{ net_id }}" ]
    validate_certs: no
    userdata: "{{ cloudinit }}"
    meta:
      hostname: "{{ instance_name }}"
      group: "{{ group }}"

- name: Add hosts to inventory
  add_host:
    name: "{{ os_hosts['server']['public_v4'] }}"
    ansible_user: "{{ instance_manage_user }}"
    groups: "{{ group }}"
    instance_name: "{{ os_hosts['server']['name'] }}"
    ansible_host: "{{ os_hosts['server']['public_v4'] }}"
    private_ip: "{{ os_hosts['server']['private_v4'] }}"

- name: 123
  debug:
    msg: "{{ hostvars[groups['master'][0]] }}"

- name: 123
  debug:
    msg: "==============================="

- name: 123
  debug:
    msg: "{{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}"

- name: Wait for system to become reachable
  wait_for_connection:
    timeout: "{{ waiter_timeout }}"
