- name: "Create flavor that will be used for master node"
  os_nova_flavor:
    validate_certs: no
    cloud: "{{ cloud }}"
    state: present
    name: "{{ master_flavor_name }}"
    # TODO (msenin): get from vars
    ram: 4096
    vcpus: 2
    disk: 30
    ephemeral: 30

- name: "Create flavor that will be used for slave instances"
  os_nova_flavor:
    validate_certs: no
    cloud: "{{ cloud }}"
    state: present
    name: "{{ slave_flavor_name }}"
    # TODO (msenin): get from vars
    ram: 1024
    vcpus: 2
    disk: 10
    ephemeral: 0
