# Creates a key pair with the running users public key
- os_keypair:
    validate_certs: no
    cloud: "{{ cloud }}"
    state: present
    name: "keypair_name"
    public_key_file: "{{ public_key_path }}"
