- name: Receive information about the cloud from clouds.yaml
  os_client_config:
    clouds: [ "{{ cloud }}" ]

- include_tasks: "{{ item }}"
  with_items:
  - create_os_project.yml
  - create_os_flavors.yml
  - create_os_keypair.yml
#  - create_os_networks.yml
  - create_os_security_group.yml