- name: Receive information about the cloud from clouds.yaml
  os_client_config:
    clouds: [ "{{ cloud }}" ]

- name: Retrieve all available Openstack hypervisors
  os_hypervisor_facts:
          enabled: True
          active: True
          validate_certs: no

- set_fact:
        number_of_portions: "{{ (openstack_hypervisor|length / portion)|round(0, 'ceil') }}"

- import_tasks: all_templates.yml
  when: save_all_templates|default(false)|bool == true

- import_tasks: main_template.yml
  when: save_all_templates|default(false)|bool == false
