- name: Receive information about the cloud from clouds.yaml
  os_client_config:
    clouds: [ "{{ cloud }}" ]

- name: Retrieve all available Openstack hypervisors
  os_hypervisor_facts:
          enabled: True
          active: True
          validate_certs: no

- name: Render heat template
  template:
          src: heat_template.j2
          dest: ./roles/create_os_resources/templates/heat_template.yaml
          force: yes
  vars:
          openstack_hypervisors: "{{ openstack_hypervisor | flatten(levels=1) }}"
          assign_floating_ip_daemon_set: "{{ assign_floating_ip_daemon_set_param }}"
          random_instance_count: "{{ random_instance_count_param }}"
          assign_floating_ip_random_set: "{{ assign_floating_ip_random_set_param }}"

          #- name: Create heat stack
          #  register: "mons_stack"
          #  os_stack:
          #          auth: "{{ cloud }}"
          #          name: mons
          #          state: present
          #          validate_certs: no
          #          template: heat_template.yaml
          #          parameters:
          #                  internal_network_cidr: "{{ internal_network_cidr }}"
          #                  public_network_uuid: "{{ public_net_id }}"
          #                  public_network: "{{ floating_ip_pools }}"
          #                  master_image_id: "{{ master_image_id }}"
          #                  slave_image_id: "{{ slave_image_id }}"
          #                  master_instance_name: "{{ master_instance_name }}"
          #                  slave_instance_name: "{{ slave_instance_name }}"
          #                  availability_zone: "{{ availability_zone }}"
          #
          #- name: Wait for system to become reachable
          #  wait_for_connection:
          #          timeout: "{{ waiter_timeout }}"
