- name: Wait for cloud init to finish
  cloud_init_data_facts:
    filter: status
  register: res
  until: "res.cloud_init_data_facts.status.v1.stage is defined and not res.cloud_init_data_facts.status.v1.stage"
  retries: 50
  delay: 5

- name: Gather all facts of cloud init
  cloud_init_data_facts:

- name: Create system.d conf directory
  file:
    path: /etc/systemd/system.conf.d/
    state: directory
    recurse: yes

# TODO (msenin): double-check and disable
- name: Set up system proxy
  template:
    src: 10-default-env.j2
    dest: /etc/systemd/system.conf.d/10-default-env.conf
    owner: root
    group: root
    mode: 0644

- name: Create docker.service.d conf directory
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    recurse: yes

- name: Set up proxy for docker service
  template:
    src: http_proxy.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    owner: root
    group: root
    mode: 0644

- name: Update profile for PythonBrew for foo user
  lineinfile:
    dest: /etc/profile
    line: |
      export HTTP_PROXY={{ http_proxy }}
      export HTTPS_PROXY={{ http_proxy }}
    owner: root

- name: Force systemd to reread configs (2.4 and above)
  systemd: daemon_reload=yes

- name: Install prometheus node exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
