- name: Get docker sign key
  apt_key:
    url: "{{ docker_sign_key_url }}"
    state: present
  # TODO (msenin): https://github.com/ansible/ansible/issues/31691
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"

- name: Add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_repo_url }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
    update_cache: yes

- name: Install docker-ce, python3-pip packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  with_items:
    - docker-ce
    - python3-pip

- name: Upgrade pip and install docker compose
  pip: 
    name: "{{ item }}"
    extra_args: --upgrade
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ http_proxy }}"
  with_items:
    - pip
    - docker-compose
