#Set master/slave image ids
slave_image_id: 
master_image_id: 

internal_network_cidr: 10.0.0.0/24
#Set public network id
public_net_id:
#Set public network name
floating_ip_pools: public
#Set AZ
availability_zone: nova

number_of_random_instances: 3
assign_floating_ip_daemon_set_enabled: true
assign_floating_ip_random_set_enabled: false
check_internet_access_daemon_set_enabled: true
check_internet_access_random_set_enabled: false

add_google_dns_enabled: true

batch_size: 10

master_instance_name: "prometheus-master"
slave_instance_name: "prometheus-slave"
